### ISSUE TITLE
Can't find ga

### ISSUE THREAD

**Issue by stefro** [protonemedia/laravel-analytics-event-tracking#4]
Hi,

I'm using the packages as described in the docs, and added a CDN to axios since we don't use axois.

```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"
                integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ=="
                crossorigin="anonymous"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async
                src="https://www.googletagmanager.com/gtag/js?id={{ config('analytics-event-tracking.tracking_id') }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }

            gtag('js', new Date());
            gtag('config', '{{ config('analytics-event-tracking.tracking_id') }}', { 'send_page_view': false });
            gtag('event', 'page_view', {
                'event_callback': function () {
                @sendAnalyticsClientId
                }
            });
        </script>
```

When I load the page, I get the message `ReferenceError: Can't find variable: ga` in the console and the event is not sent to analytics. Do need to include another library?

Thank you in advance!

**Comment by daikazu** [comment]
I just ran into this issue with a new site that is using the new Google Analytics v4. Maybe it has something to do with that?

**Comment by pascalbaljet** [comment]
Thanks for reporting, I’ll look into it!

**Comment by pascalbaljet** [comment]
There's indeed a difference between `analytics.js` and `gtag.js`:
https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs

See also:
https://stackoverflow.com/questions/65270512/how-get-client-id-in-google-analytics-4?

There's a `gaGlobal.vid` variable that holds the Client ID, but I don't know how reliable it is.

**Comment by stefro** [comment]
@pascalbaljet 
Thanks for this information! For now, I'm going to bail on this package due to a deadline I've been given.
However the package is very nice! Great job!

**Comment by pascalbaljet** [comment]
I found it! I've just tagged v1.2.1 that should fix it 💪
https://developers.google.com/gtagjs/reference/api?hl=en#event

**Comment by stefro** [comment]
Awesome!!!

**Comment by pascalbaljet** [comment]
Don't forget to republish the view file :)

**Comment by daikazu** [comment]
Nice!  Thank you sir.  I love the simplicity and idea around this package.
